version: "3.9"

services:
  tdgt-quiz:
    image: nginx:stable-alpine
    container_name: tdgt-quiz
    restart: unless-stopped
    volumes:
      - ./:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.tdgt-quiz.rule=Host(`chat.tdgt.grunenberg.org`)"
      - "traefik.http.routers.tdgt-quiz.entrypoints=websecure"
      - "traefik.http.routers.tdgt-quiz.tls.certresolver=lets-encrypt"
      - "traefik.http.services.tdgt-quiz.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    external: true
